### ISSUE TITLE
Inclusive language should be used to follow current global trends

### ISSUE THREAD

**Issue by cocus** [frankdilu/CheLang#1]
This language is amazing, however it was of course designed and programmed by a patriarch.
The error messages should use the inclusive language versions. Current global trends forces us to use such gender-less language instead of the old and outdated binary and gender-based spanish.

For instance "s/Flaco/Flaque" (Or any other variations of that word, choose the worst sounding one).

**Comment by dalepo** [comment]
I propose change `andaPor` for `andePor` to be more inclusive

**Comment by francodilu** [comment]
Hmm the language must be the most argento possible, so i think no-inclusive is better
