### ISSUE TITLE
variante de declaración de variables

### ISSUE THREAD

**Issue by nallegrotti** [frankdilu/CheLang#16]
me parece que le daría un buén estilo de las variables se declaren con un "digamos que" o "onda"

```cheLang
onda a es 1
digamos que b es 2
che c es 3

ponele que a anda por 1 y b anda por 2 y c anda por 3 tonce cuchame("piola") aLoSumo cuchame("todo mal") hastaAca
```

**Comment by francodilu** [comment]
jajajajajajaj seeeee. El de digamos que lo voy a poner, el onda no me convence. Sos groso.
