### ISSUE TITLE
Che la sintaxis podría ser mejor

### ISSUE THREAD

**Issue by soypat** [frankdilu/CheLang#2]
Seeing as there is no code of conduct or contributing guidelines yet, forgive the title.

I'll be grouping several sintaxis recommendations in one issue because they really stand out as bad decisions from the get-go to me.

### es andapor
The `messi es andaPor 10` as `messi == 10` does not sound good on the tongue.  **Proposal:** Using just `andapor` would arguably sound more argento.

### multiple variable declaration
This can be a hell of a lot to write just to declare a couple of variables. If you want your language to be successful, and I *know* it will be because who doesen't want to operate on numbers with `ma` and `meno`, then you gotta figure a shorthand way of doing it. **Proposals:** 

`che messi, maradona, batistuta son 10, 10, 9` // son could also be `es`
`che ricky_fort, mirtha son 100` 

### Inequality conditions
Maybe rename them for easier writing. I admit I'm not sure how and what I would change but I would argue there's room for improvement.
|Operator|  Argento |
|-----|---|
|  < | `cachitomenoque`   |
|  >     | `cachitomaque`    |
| >=  |  `mayoigual`  |
|<=   |  `menoigual` |
| !=  | `nadakever` |

I'd stick with the all lowercaps convention, less of a headache to write and as they say: *se entiende, no?*

**Comment by francodilu** [comment]
Hi men! A lot of tenkius, it is really helpful. About "es andaPor" yes, it will be just "andaPor", today i wasn't time to fix it.

About declaring variables i like that, if i can it will be something like that.

And about the conditions,  i love the `nakever`.

Tomorrow i will take a look all this

Pd: sorry,  camelCase is the best

Pd2: i must make a conduct / contributing guidelines.

**Comment by francodilu** [comment]
Update:
Just `andaPor` **Done**.

`nakever` not equal operation **Done**. (not commited yet)

**Comment by GuidoDipietro** [comment]
As a side note to this, I'd like to point out that ```nakever``` comes across (to the 'English eye') as having some kind of relation with 'nake' or 'naked', by just catching a brief glimpse of it.  
I'd suggest that you change the spelling of that keyword to ```naquever```.

**Comment by francodilu** [comment]
Hm idk... This language is pointing to argentos, not to yankis... But maybe.

Maybe i can make a pull about that, i will see.
