### ISSUE TITLE
Error en es nakever

### ISSUE THREAD

**Issue by jvasque** [frankdilu/CheLang#21]
Actualmente la función se encuentra así (igual a "no es"): 
es nakever   => !=

Debería ser así:
es nakever   => !==

Todo sea para un correcto uso del lenguaje y de aquellos novatos que lo vayan a usar.

**Comment by francodilu** [comment]
Oopse, no me habia dado cuenta... Ahi corrijo la docu! Tenkia!
pd: sorry la tardanza(?

**Comment by francodilu** [comment]
Done! Gracias por la colaboracion!
