### ISSUE TITLE
Ameo, I think you're missing a "self"

### ISSUE THREAD

**Issue by GuidoDipietro** [frankdilu/CheLang#5]
My dearest frankdilu,

upon venturing into the unknown realms of CheLang I spotted the following issue.

I coded a simple loop equivalent to the following in Python:
```
num = input("Do be as kind as to provide me with a num: ")
def curlyHair(n):
   while n > 0:
      n = n-1

curlyHair(int(num))
# Doesn't return anything, just executes the 'while' loop
# a total of 'num' times, doesn't even modify the global value of 'num'
```
Let me provide a screenshot of the CheLang/argento translation of said snippet, together with the Console logs:

![image](https://user-images.githubusercontent.com/48221146/85185797-fc28d280-b26b-11ea-8325-c64e7911ce76.png)

I should mention that this was the first Error I run into that wasn't addressed by the CheLang interpreter.

Is this an actual bug or am I coding _para el carajo_?

I can't wait to use a stable version of CheLang. The world will be a better place by then.

Ninos()

**Comment by francodilu** [comment]
Hey! Thanks! My fault. When i implement the Empty class i miss the () when i return it. Fixed, commiting. Thx a lot.
