### ISSUE TITLE
Error al ejecutar archivo .che con doble click

### ISSUE THREAD

**Issue by GuidoDipietro** [frankdilu/CheLang#9]
![image](https://user-images.githubusercontent.com/48221146/87729669-42eee700-c79c-11ea-84d7-f2476d00f1b8.png)

Tengo bien las variables de entorno. ¿Alguna idea?

**Comment by francodilu** [comment]
Es culpa de Python y su manejo de los \ .

**Comment by frankdilu** [comment]
Subiendo la release denuevo con el fix.

**Comment by francodilu** [comment]
Descarga denuevo la release v1.2.0 que la actualice
